sudo: required
notifications:
  email:
    recipients:
      - groonga-commit@lists.osdn.me
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.3
  - 2.5.0
before_install:
  - curl --silent --location https://raw.githubusercontent.com/groonga/groonga/master/data/travis/setup.sh | sh
  - gem update bundler
